WIP Account deletion request
biocore/microsetta-interface pull request #225
Opened 2022-07-26 21:55 UTC by charles-cowart

Implementation for Account Deletion Request.
Work in Progress: Send final email confirmation after deletion + some unittests not implemented.

2022-07-26 22:08 UTC, charles-cowart commented on microsetta_interface/implementation.py
> +def post_request_account_removal(*, account_id=None):
check for prerequisites for account status

2022-07-26 22:11 UTC, charles-cowart commented on microsetta_interface/implementation.py
> +def post_request_account_removal(*, account_id=None):
HOME_PREREQS_MET is likely needed.

2022-07-26 22:13 UTC, charles-cowart commented on microsetta_interface/templates/account_removal.jinja2
> +                <i>{{ _('Account ID') }}</i>
Display email + name, rather than Account ID

2022-08-02 21:38 UTC, charles-cowart commented
@cassidysymons This PR is passing integration tests locally. Reviewing CI logs shows that the stock microsetta-private-api is being installed for testing. This is most likely the reason it's failing to do so in CI because it relies on changes to microsetta-private-api that are not yet merged.

2022-08-02 21:40 UTC, cassidysymons commented
@charles-cowart Agreed, as long as that's the only test failing it's a non-issue. Assuming things look good after code review, we can merge the Private API PR, then re-run integration tests to confirm no further issues here.

2022-08-02 22:52 UTC, charles-cowart commented on microsetta_interface/implementation.py
> +    # PUT is used to add the account_id to the queue
confirm

2022-08-02 22:55 UTC, charles-cowart commented on microsetta_interface/routes.yaml
> +    post:
confirm

2022-08-02 22:56 UTC, charles-cowart commented on microsetta_interface/templates/account_removal.jinja2
> +    <a href="/admin/campaigns/edit">Add New Campaign</a>
confirm

2022-08-03 21:19 UTC, charles-cowart commented on microsetta_interface/implementation.py
> +    # PUT is used to add the account_id to the queue
confirmed this is the endpoint called by the 'Delete Account' button in Accounts Details page.

2022-08-03 21:20 UTC, charles-cowart commented on microsetta_interface/routes.yaml
> +    post:
confirmed this is the endpoint called by the 'Delete Account' button in the Accounts Details page.

2022-08-03 23:40 UTC, cassidysymons requested changes

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/implementation.py
> +# same as above.
Can you clarify this comment in case someone eventually sticks a function between post_remove_source() and post_request_account_removal()?

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/routes.yaml
> +  '/admin/requests/account_removal/list':
```suggestion
  '/admin/account_removal/list':
```

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/templates/admin_requests_account_removal_list.jinja2
> +{% set page_title = _("Admin Address Verification") %}
Can you fix the page title?

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/templates/admin_requests_account_removal_list.jinja2
> +                  <button type=submit" class="btn btn-danger">{{ _('Delete') }}</button>
```suggestion
                  <button type="submit" class="btn btn-danger">{{ _('Delete') }}</button>
```

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/templates/admin_requests_account_removal_list.jinja2
> +                  <button type=submit" class="btn btn-danger">{{ _('Ignore') }}</button>
```suggestion
                  <button type="submit" class="btn btn-danger">{{ _('Ignore') }}</button>
```

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/templates/request_account_deletion_confirm.jinja2
> +{% set hide_header = True %}
There's no reason to hide the header here.
```suggestion
```

2022-08-03 23:40 UTC, cassidysymons commented on microsetta_interface/tests/test_integration.py
> +print("Private API Available: %s" % PRIVATE_API_AVAILABLE)
Can this be removed?

2022-08-31 22:41 UTC, charles-cowart commented on microsetta_interface/templates/account_removal.jinja2
> +    <a href="/admin/campaigns/edit">Add New Campaign</a>
confirmed vestigial template removed.

2022-08-31 23:13 UTC, charles-cowart commented
@cassidysymons Ready for review/approval/merge.

2022-09-02 17:00 UTC, charles-cowart commented
@cassidysymons Confirmed test_request_delete() consistency passes locally. Usually this test fails because a user is not logged in and the message we're testing for isn't rendered. I'm not sure yet why the behavior is different in CI but I'm looking into it.

2022-09-03 03:36 UTC, charles-cowart commented
Confirmed this error is caused by the integration test dependency 'microsetta-private-api'. The test fails because get_account_details() calls microsetta-private-api->/accounts/{account_id}/removal_queue to determine if the account is already in the removal queue. It will use this information to present either the 'request account deletion' button or a message to the user preventing them from requesting account deletion more than once.

Since this endpoint is not present in microsetta-private-api 'master', https://github.com/biocore/microsetta-private-api/pull/447 must be merged before this integration test will pass.

Confirmed in Ubuntu 20.04 VM running freshly cloned repos, testing against a different branch in microsetta-private-api and then the branch from the PR above:

< GET /api/accounts/<user_uuid>/removal_queue?language_tag=en_US HTTP/1.1" 404 -
---
> GET /api/accounts/<user_uuid>/removal_queue?language_tag=en_US HTTP/1.1" 200 -

2022-12-16 06:43 UTC, cassidysymons commented
Please back out the commits that got pushed through when I updated biocore:master - I need to merge those from master to master-overhaul later.

2023-01-06 22:24 UTC, cassidysymons commented
@charles-cowart Can you please make sure your branch is current with biocore/master-overhaul to resolve the conflicts?

Thanks.

2023-01-06 23:43 UTC, cassidysymons commented
There are a ton of changes in this PR that shouldn't be there, it looks like its head branch might be an old version of master? And there's a partially fixed conflict in implementation.py that left artifacts in the code - https://github.com/biocore/microsetta-interface/pull/225/files#diff-d0d9d8f03fadc97c50240e568080abb22c7a13c39b137f62126161dfaeddb86cR797 . Can you take a look and make sure that only the changes relevant to account deletion request are a part of the PR?

2023-01-06 23:59 UTC, charles-cowart commented
> There are a ton of changes in this PR that shouldn't be there, it looks like its head branch might be an old version of master? And there's a partially fixed conflict in implementation.py that left artifacts in the code - https://github.com/biocore/microsetta-interface/pull/225/files#diff-d0d9d8f03fadc97c50240e568080abb22c7a13c39b137f62126161dfaeddb86cR797 . Can you take a look and make sure that only the changes relevant to account deletion request are a part of the PR?

Yeah. When I created the branch, master-overhaul likely didn't exist yet; I did have to add biocore as an upstream and pull the master-overhaul branch to merge it. Not sure why there would be changes that shouldn't be there, unless the older code is now being considered a change.

Would the best thing to do is isolate the relevant changes, create a new branch from the current master-overhaul, and apply them to the new branch? I'm not sure.

2023-01-07 00:04 UTC, cassidysymons commented
Yeah, I think that would be the cleanest approach.

2023-01-07 01:17 UTC, charles-cowart commented
Closing. Relevant code changes have been applied to master-overhaul branch and PR https://github.com/biocore/microsetta-interface/pull/267 was issued.

2023-01-07 01:17 UTC, closed without merging