Updates for Spanish (es_MX & es_ES) + responsiveness adjustments
biocore/microsetta-interface pull request #274
Opened 2023-02-28 20:36 UTC by cassidysymons

WIP - Deploying to Staging for Alejandra to review new translations in context and opening PR to confirm no Lint/test issues. Will update PR and mark for review once it's ready.

2023-03-20 20:18 UTC, wasade requested changes
Mostly small comments, thanks!

2023-06-05 00:18 UTC, cassidysymons commented on microsetta_interface/static/vue_survey_form_es_es.js
> +var vm = new Vue({
I re-centralized it into one JS file and used global variables to expose the necessary strings to flask babel.

2023-06-05 00:20 UTC, cassidysymons commented on microsetta_interface/translations/es_ES/LC_MESSAGES/messages.po
> +#~ msgid "A fermented foods specific questionnaire"
They're translations that no longer exist in the source files. I purged them from each of the PO files, which should/will be a part of the translation cycle on an ongoing basis.

2023-06-06 21:22 UTC, wasade approved these changes

2023-06-06 21:22 UTC, merged