Two New UI Features
biocore/microsetta-interface pull request #275
Opened 2023-03-12 01:01 UTC by cassidysymons

1) Adds support for a "test mode" system message that indicates that users should stay off the platform.
2) When a user logs sample information, it checks when they last updated their surveys - if it has been over a week, it prompts them to review their survey answers.

This PR should be merged after https://github.com/biocore/microsetta-interface/pull/274

2023-03-12 01:02 UTC, cassidysymons commented
Leaving it as a draft for the moment as the Spanish translations for the new messages need to be dropped in on Monday morning.

2023-04-04 20:45 UTC, wasade requested changes
Thanks! Most comments are minor. It would I think be valuable to decompose the common logic in the `vue_survey_form_*.js` scripts though as the duplications represent a maintenance burden (and avenue for bugs) should that logic need to be modified in the future

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/implementation.py
> +    # Check the FFQ prereqs for the source (birth year, gender, height, weight
```suggestion
    # Check the FFQ prereqs for the source (birth year, gender, height, weight)
```

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/static/vue_survey_form_es_mx.js
> +        prettyJSON: function(json) {
A lot of the stuff here and below looks like it's replicated across multiple files. Can the common logic be centralized?

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/templates/kits.jinja2
> +            {% for kit_samples in kits.values() %}
Was the sort not working?

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/templates/kits.jinja2
> +                                        Info Needed
```suggestion
                                        {{ _('Info Needed') }}
```

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/templates/nutrition.jinja2
> +            });*/
```suggestion
```

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/templates/source.jinja2
> +                            {% if detail.survey_template_id == 10 %}
Could `10` be replaced with a named variable at the top of the template?

2023-04-04 20:45 UTC, wasade commented on microsetta_interface/translations/en_US/LC_MESSAGES/messages.po
> +
```suggestion
```

2023-06-16 19:32 UTC, closed without merging